--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
-- Dumped by pg_dump version 15.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product; Type: TABLE; Schema: public; Owner: weppo_admin
--

CREATE TABLE public.product (
    id integer NOT NULL,
    name text NOT NULL,
    price numeric NOT NULL,
    description text NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE public.product OWNER TO weppo_admin;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: weppo_admin
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: weppo_admin
--

COPY public.product (id, name, price, description, quantity) FROM stdin;
1	Betoniarka	123.45	fajna rzecz	100
2	Kremówka	213.7	xD	2137
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: weppo_admin
--

SELECT pg_catalog.setval('public.product_id_seq', 3, true);


--
-- Name: product product_pk; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pk PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

