--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
-- Dumped by pg_dump version 15.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: order_set_completed_at(); Type: FUNCTION; Schema: public; Owner: weppo_admin
--

CREATE FUNCTION public.order_set_completed_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
	begin
		if old.completed = false and new.completed = true then
			NEW.completed_at := now();
		end if;
		RETURN NEW;
	END;
$$;


ALTER FUNCTION public.order_set_completed_at() OWNER TO weppo_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_entry; Type: TABLE; Schema: public; Owner: weppo_admin
--

CREATE TABLE public.cart_entry (
    id integer NOT NULL,
    user_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT cart_entry_check_quantity CHECK ((quantity > 0))
);


ALTER TABLE public.cart_entry OWNER TO weppo_admin;

--
-- Name: cart_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: weppo_admin
--

ALTER TABLE public.cart_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hash; Type: TABLE; Schema: public; Owner: weppo_admin
--

CREATE TABLE public.hash (
    id integer NOT NULL,
    user_id integer NOT NULL,
    hash text NOT NULL
);


ALTER TABLE public.hash OWNER TO weppo_admin;

--
-- Name: hash_id_seq; Type: SEQUENCE; Schema: public; Owner: weppo_admin
--

ALTER TABLE public.hash ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hash_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order; Type: TABLE; Schema: public; Owner: weppo_admin
--

CREATE TABLE public."order" (
    id integer NOT NULL,
    buyer_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    ordered_at timestamp without time zone DEFAULT now() NOT NULL,
    successful boolean DEFAULT false NOT NULL,
    completed_at timestamp without time zone DEFAULT now() NOT NULL,
    completed boolean DEFAULT false NOT NULL
);


ALTER TABLE public."order" OWNER TO weppo_admin;

--
-- Name: order_id_seq; Type: SEQUENCE; Schema: public; Owner: weppo_admin
--

ALTER TABLE public."order" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: weppo_admin
--

CREATE TABLE public.product (
    id integer NOT NULL,
    name text NOT NULL,
    price numeric NOT NULL,
    description text NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE public.product OWNER TO weppo_admin;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: weppo_admin
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: weppo_admin
--

CREATE TABLE public.role (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.role OWNER TO weppo_admin;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: weppo_admin
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: weppo_admin
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL
);


ALTER TABLE public."user" OWNER TO weppo_admin;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: weppo_admin
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: userrole; Type: TABLE; Schema: public; Owner: weppo_admin
--

CREATE TABLE public.userrole (
    id integer NOT NULL,
    user_id integer NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public.userrole OWNER TO weppo_admin;

--
-- Name: userrole_id_seq; Type: SEQUENCE; Schema: public; Owner: weppo_admin
--

ALTER TABLE public.userrole ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.userrole_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_entry cart_entry_pk; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.cart_entry
    ADD CONSTRAINT cart_entry_pk PRIMARY KEY (id);


--
-- Name: hash hash_pk; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.hash
    ADD CONSTRAINT hash_pk PRIMARY KEY (id);


--
-- Name: order order_pk; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_pk PRIMARY KEY (id);


--
-- Name: product product_pk; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pk PRIMARY KEY (id);


--
-- Name: role role_pk; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pk PRIMARY KEY (id);


--
-- Name: user user_email_unique; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_unique UNIQUE (email);


--
-- Name: user user_pk; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pk PRIMARY KEY (id);


--
-- Name: userrole userrole_pk; Type: CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.userrole
    ADD CONSTRAINT userrole_pk PRIMARY KEY (id);


--
-- Name: order order_set_completed_at; Type: TRIGGER; Schema: public; Owner: weppo_admin
--

CREATE TRIGGER order_set_completed_at BEFORE UPDATE ON public."order" FOR EACH ROW EXECUTE FUNCTION public.order_set_completed_at();


--
-- Name: cart_entry cart_entry_product_fk; Type: FK CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.cart_entry
    ADD CONSTRAINT cart_entry_product_fk FOREIGN KEY (product_id) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: cart_entry cart_entry_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.cart_entry
    ADD CONSTRAINT cart_entry_user_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: hash hash_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.hash
    ADD CONSTRAINT hash_user_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: order order_product_fk; Type: FK CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_product_fk FOREIGN KEY (product_id) REFERENCES public.product(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: order order_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_user_fk FOREIGN KEY (buyer_id) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: userrole userrole_role_fk; Type: FK CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.userrole
    ADD CONSTRAINT userrole_role_fk FOREIGN KEY (role_id) REFERENCES public.role(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: userrole userrole_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: weppo_admin
--

ALTER TABLE ONLY public.userrole
    ADD CONSTRAINT userrole_user_fk FOREIGN KEY (user_id) REFERENCES public."user"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO weppo_admin;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: weppo_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE weppo_admin IN SCHEMA public GRANT ALL ON SEQUENCES  TO weppo_admin;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: weppo_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE weppo_admin IN SCHEMA public GRANT ALL ON FUNCTIONS  TO weppo_admin;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: weppo_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE weppo_admin IN SCHEMA public GRANT ALL ON TABLES  TO weppo_admin;


--
-- PostgreSQL database dump complete
--

